config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :tweets, except: [:edit, :update] do 
    resources :comments, only: [:create, :destroy]
    member do 
      post :retweet
    end
  end
  
  resources :profiles
  resources :likes, only: :create


  devise_for :users
  root to: 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likeable
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  include Likeable
  belongs_to :user
  belongs_to :tweet, optional: true
  has_many :comments

  validates :body, length: { maximum: 240 }, allow_blank: false, unless: :tweet_id

  def tweet_type
    if tweet_id? && body?
      "quote-tweet"
    elsif tweet_id?
      "retweet"
    else
      "tweet"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
pay_customer

has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets

  validates_uniqueness_of :username

  has_one_attached :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :profile_image])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tweet

    def create
      @comment = @tweet.comments.new(comment_params.merge(user: current_user))
      respond_to do |format|
        if @comment.save
          format.turbo_stream
        else
          format.html { redirect_to tweet_path(@tweet), alert: "Reply could not be created"}
        end
      end         
    end

    def destroy
      @comment = @tweet.comments.find(params[:id])
      @comment.destroy

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to tweet_path(@tweet), notice: "Comment was deleted" }
      end
    end

    private

    def comment_params
        params.require(:comment).permit(:body)
    end

    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/concerns/likeable.rb
module Likeable
  extend ActiveSupport::Concern

  included do
    has_many :likes, as: :likeable
  end

  def liked_by?(user)
    likes.where(user: user).any?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_likeable

  def create
    if @likeable.likes.count >= 1 && @likeable.liked_by?(current_user)
      @like = Like.find_by(likeable_id: @likeable.id, user: current_user)
      @like.destroy
    else
      @like = @likeable.likes.new
      @like.user = current_user
      @like.save
    end
  end

  private

  def set_likeable
    @likeable = params[:likeable_type].constantize.find(params[:likeable_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = User.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    
    respond_to do |format|
      if @tweet.save
        format.turbo_stream
      else
        format.html do 
          flash[:tweet_errors] = @tweet.errors.full_messages
          redirect_to root_path
        end      
      end
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.order(created_at: :desc)
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
  end

  def retweet
    @tweet = Tweet.find(params[:id])

    @retweet = current_user.tweets.new(tweet_id: @tweet.id)

    respond_to do |format|
      if @retweet.save
        format.turbo_stream
      else
        format.html { redirect_back fallback_location: @tweet, alert: "Could not retweet" }
      end
    end
  end

  private

    def tweet_params
      params.require(:tweet).permit(:body)
    end   
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(flash_type)
    flash_base = "px-2 py-4 mx-auto font-sans font-medium text-center text-white"
    {
      notice: "bg-indigo-600 #{flash_base}",
      error:  "bg-red-600 #{flash_base}",
      alert: "bg-red-600 #{flash_base}"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def nav_classes
    ["devise/registrations", "devise/sessions", "devise/confirmations", "devise/passwords", "devise/unlocks"].include?(params[:controller]) ? "hidden" : nil
  end

  def label_class(options={})
    "block mb-1 font-normal leading-normal #{options[:extended_classes]}"
  end

  def input_class(options={})
    "rounded border border-gray-300 block w-full focus:outline-none focus:border-gray-400 outline-none focus-within:outline-none focus:ring-2 focus:ring-gray-200 #{options[:extended_classes]}"
  end

  def checkbox_class(options={})
    "rounded border-gray-300 border focus:ring-2 focus:ring-gray-200 text-blue-500 mr-1 #{options[:extended_classes]}"
  end

  def link_class(options={})
    "text-gray-700 underline hover:no-underline hover:text-gray-800 block #{options[:extended_classes]}"
  end

  def button_class(options={})
    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  def theme_button(theme)
    themes = {
      primary: "primary",
      secondary: "secondary",
      transparent: "transparent",
      dark: "dark"
    }

    case theme
    when themes[:primary]
      "bg-sky-500 hover:bg-sky-600 text-white"
    when themes[:secondary]
      "bg-teal-600 hover:bg-teal-700 text-white"
    when themes[:transparent]
      "bg-transparent hover:bg-gray-100 text-gray-700"
    when themes[:dark]
      "bg-gray-800 text-white shadow-sm hover:bg-gray-900"
    else
      "bg-white border border-gray-300 shadow-sm hover:bg-gray-100"
    end
  end

  def style_button(variant, theme)
    base = "rounded text-center font-sans font-normal outline-none leading-normal cursor-pointer transition ease-in-out duration-200 font-medium"

    case variant
    when "large"
      "px-5 py-4 text-lg #{base} #{theme}"
    when "small"
      "py-2 px-4 text-sm #{base} #{theme}"
    when "expanded"
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end

  def profile_image(user, options={})
    size = case options[:size]
    when "large"
      "w-20 h-20"
    when "small"
      "w-10 h-10"
    else
      "w-14 h-14"
    end

    classes = "#{size} flex-shrink-0 rounded-full border-2 border-white"

    if user.profile_image.attached?
      image_tag user.profile_image, class: classes
    else
      image_tag "https://doodleipsum.com/700/avatar-5?bg=3D27F6&i=f339578a64040310d3eb5bd82b550627", class: classes
    end

  end


end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="py-4 border-b" id="<%= dom_id(comment) %>">
  <div class="flex space-x-3 items-start">
    <div>
    <%= profile_image(comment.user) %>
    </div>
    <div class="flex-1">
      <p class="font-bold"><%= link_to comment.user.name, profile_path(comment.user), class: "hover:underline", data: { turbo: false } %></p>
      <div class="prose prose-lg"><%= comment.body %></div>

      <ul class="-ml-3 flex space-x-14 items-start justify-start list-none">
        <li>
          <%= content_tag :div, class: "#{dom_id(comment)}_likes" do %>
            <%= render "likes/likes", likeable: comment %>
          <% end %>
        </li>
        <% if user_signed_in? && current_user == comment.user  %>
          <li>
            <%= button_to tweet_comment_path(comment.tweet,comment), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "text-gray-500 space-x-2 group flex items-center justify-center" do %>
              <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-gray-50">
                <svg viewBox="0 0 24 24" aria-hidden="true" class="fill-current text-gray-500 group-hover:text-rose-500 w-5 h-5"><g><path d="M20.746 5.236h-3.75V4.25c0-1.24-1.01-2.25-2.25-2.25h-5.5c-1.24 0-2.25 1.01-2.25 2.25v.986h-3.75c-.414 0-.75.336-.75.75s.336.75.75.75h.368l1.583 13.262c.216 1.193 1.31 2.027 2.658 2.027h8.282c1.35 0 2.442-.834 2.664-2.072l1.577-13.217h.368c.414 0 .75-.336.75-.75s-.335-.75-.75-.75zM8.496 4.25c0-.413.337-.75.75-.75h5.5c.413 0 .75.337.75.75v.986h-7V4.25zm8.822 15.48c-.1.55-.664.795-1.18.795H7.854c-.517 0-1.083-.246-1.175-.75L5.126 6.735h13.74L17.32 19.732z"></path><path d="M10 17.75c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75zm4 0c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75z"></path></g></svg>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [tweet, @comment], data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |form| %>
  <p class="pt-3">Replying to <%= link_to tweet.user.name, profile_path(tweet.user), class: "text-sky-500 hover:text-sky-600" %></p>
  <div class="flex items-start justify-between space-x-3 py-6 border-b">
    <%= profile_image(current_user) %>
    <div class="flex-1">
      <%= form.label :body, class: "sr-only" %>
      <%= form.text_area :body, class: "border-none w-full resize-none rounded-md focus:shadow-none focus:border-none ring-0 focus:ring-0 focus:outline-none text-lg py-3 px-0 h-full min-h-[100px]", placeholder: "Tweet your reply:"%>
    </div>
    <%= form.submit "Reply", class: "px-6 py-2 bg-sky-400 text-white font-semibold rounded-full text-center cursor-pointer inline-block hover:bg-sky-500 transition ease-in-out duration-300"%>
    </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%=  turbo_stream.prepend "#{dom_id(@tweet)}_comments" do %>
  <%= render "comment", comment: @comment %>
<% end %>

<%= turbo_stream.replace "#{dom_id(@tweet)}_comments_count" do %>
  <%= render "tweets/comments_count", tweet: @tweet  %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove(@comment) %>

<%= turbo_stream.replace "#{dom_id(@tweet)}_comments_count" do %>
  <%= render "tweets/comments_count", tweet: @tweet  %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white flex flex-col min-h-screen ">

    <header>
      <%= render "shared/flash_notice" %>
    </header>

    <main class="flex-grow container mx-auto px-4">
      <div class="grid lg:grid-cols-12 grid-cols-1 h-screen pr-6">
        <div class="lg:col-span-2 pt-6 pr-6">
          <%= link_to root_path, class:"link text-xl tracking-tight font-black" do %>
            <span class="text-sky-500">Twitter_clone</span>
          <% end %>
          <ul class="mt-6">
            <li>
              <%= link_to root_path, class: "rounded-full px-4 -ml-4 inline-flex items-center py-3 hover:bg-neutral-50 w-full text-lg transition ease-in-out duration-500" do %>
                <svg viewBox="0 0 24 24" aria-hidden="true" class="fill-current w-6 h-6 mr-4"><g><path d="M22.46 7.57L12.357 2.115c-.223-.12-.49-.12-.713 0L1.543 7.57c-.364.197-.5.652-.303 1.017.135.25.394.393.66.393.12 0 .243-.03.356-.09l.815-.44L4.7 19.963c.214 1.215 1.308 2.062 2.658 2.062h9.282c1.352 0 2.445-.848 2.663-2.087l1.626-11.49.818.442c.364.193.82.06 1.017-.304.196-.363.06-.818-.304-1.016zm-4.638 12.133c-.107.606-.703.822-1.18.822H7.36c-.48 0-1.075-.216-1.178-.798L4.48 7.69 12 3.628l7.522 4.06-1.7 12.015z"></path><path d="M8.22 12.184c0 2.084 1.695 3.78 3.78 3.78s3.78-1.696 3.78-3.78-1.695-3.78-3.78-3.78-3.78 1.696-3.78 3.78zm6.06 0c0 1.258-1.022 2.28-2.28 2.28s-2.28-1.022-2.28-2.28 1.022-2.28 2.28-2.28 2.28 1.022 2.28 2.28z"></path></g></svg>
                <span>Home</span>
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to profile_path(current_user), class: "rounded-full px-4 -ml-4 inline-flex items-center py-3 hover:bg-neutral-50 w-full text-lg transition ease-in-out duration-500" do %>
                  <svg class="fill-current w-6 h-6 mr-4"  viewBox="0 0 24 24" aria-hidden="true"><g><path d="M12 11.816c1.355 0 2.872-.15 3.84-1.256.814-.93 1.078-2.368.806-4.392-.38-2.825-2.117-4.512-4.646-4.512S7.734 3.343 7.354 6.17c-.272 2.022-.008 3.46.806 4.39.968 1.107 2.485 1.256 3.84 1.256zM8.84 6.368c.162-1.2.787-3.212 3.16-3.212s2.998 2.013 3.16 3.212c.207 1.55.057 2.627-.45 3.205-.455.52-1.266.743-2.71.743s-2.255-.223-2.71-.743c-.507-.578-.657-1.656-.45-3.205zm11.44 12.868c-.877-3.526-4.282-5.99-8.28-5.99s-7.403 2.464-8.28 5.99c-.172.692-.028 1.4.395 1.94.408.52 1.04.82 1.733.82h12.304c.693 0 1.325-.3 1.733-.82.424-.54.567-1.247.394-1.94zm-1.576 1.016c-.126.16-.316.246-.552.246H5.848c-.235 0-.426-.085-.552-.246-.137-.174-.18-.412-.12-.654.71-2.855 3.517-4.85 6.824-4.85s6.114 1.994 6.824 4.85c.06.242.017.48-.12.654z"></path></g></svg>
                  <span>Profile</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="lg:col-span-6 border-x">
          <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
        <div class="lg:col-span-4 pl-6 pt-6">
          <div class="bg-gray-50 w-full min-h-[150px] rounded-lg p-6 mb-6">Sidebar stuff</div>
          <% if user_signed_in? %>
            <p class="mb-4">
              Signed in as <%= current_user.name %>
            </p>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: button_class(theme: "primary"), data: { turbo: false } %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: button_class(theme: "primary") %>
          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-full antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white flex flex-col min-h-screen">

    <header>
      <%= render "shared/flash_notice" %>
    </header>

    <main>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/likes/_likes.html.erb
<%= button_to likes_path(likeable_id: likeable.id, likeable_type: likeable.model_name.name), method: :post, class: "text-gray-500 space-x-2 group flex items-center justify-center" do %>
  <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-rose-50">
    <% if likeable.liked_by?(current_user) %>
      <svg viewBox="0 0 24 24" aria-hidden="true" class="w-5 h-5 fill-current text-rose-500"><g><path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12z"></path></g></svg>
    <% else %>
      <svg viewBox="0 0 24 24" aria-hidden="true" class="w-5 h-5 fill-current group-hover:text-rose-500"><g><path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12zM7.354 4.225c-2.08 0-3.903 1.988-3.903 4.255 0 5.74 7.034 11.596 8.55 11.658 1.518-.062 8.55-5.917 8.55-11.658 0-2.267-1.823-4.255-3.903-4.255-2.528 0-3.94 2.936-3.952 2.965-.23.562-1.156.562-1.387 0-.014-.03-1.425-2.965-3.954-2.965z"></path></g></svg>
    <% end %>
  </div>
  <span class="group-hover:text-rose-500 text-gray-500">
    <div class="<%= dom_id(likeable) %>_likes-size"><%= likeable.likes.size %></div>
  </span>
<% end %>

app/views/tweets/_comments_count.html.erb
<span class="group-hover:text-sky-500 text-gray-500"><%= tweet.comments.count ||= 0 %></span>

app/views/tweets/_controls.html.erb
<ul class="-ml-3 flex space-x-14 items-start justify-start list-none">
  <li>
    <%= link_to tweet, class: "text-gray-500 space-x-2 group flex items-center justify-center", data: { turbo: false } do %>
      <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-sky-50">
        <svg viewBox="0 0 24 24" aria-hidden="true" class="w-5 h-5 fill-current group-hover:text-sky-500"><g><path d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z"></path></g></svg>
      </div>
      <%= turbo_frame_tag "#{dom_id(tweet)}_comments_count" do %>
        <%= render "tweets/comments_count", tweet: tweet %>
      <% end %>
    <% end %>
  </li>
   <% if user_signed_in? && tweet.user_id != current_user.id %>
    <li>
      <%= button_to retweet_tweet_path(tweet), method: :post, class:"text-gray-500 space-x-2 group flex items-center justify-center" do %>
        <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-green-50">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="w-5 h-5 fill-current group-hover:text-green-500"><g><path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z"></path></g></svg>
        </div>
        <span class="group-hover:text-green-500 text-gray-500"><%= Tweet.where(tweet_id: tweet).size %></span>
      <% end %>
    </li>
  <% end %>  
  <li>
    <%= content_tag :div, class: "#{dom_id(tweet)}_likes" do %>
      <%= render "likes/likes", likeable: tweet %>
    <% end %>
  </li>
  <% if user_signed_in? && current_user == tweet.user %>
    <li>
      <%= button_to tweet_path(tweet), method: :delete, form: { data: { turbo_confirm: "Are you sure?" }}, class:"text-gray-500 space-x-2 group flex items-center justify-center" do %>
        <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-gray-50">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="fill-current text-gray-500 group-hover:text-rose-500 w-5 h-5"><g><path d="M20.746 5.236h-3.75V4.25c0-1.24-1.01-2.25-2.25-2.25h-5.5c-1.24 0-2.25 1.01-2.25 2.25v.986h-3.75c-.414 0-.75.336-.75.75s.336.75.75.75h.368l1.583 13.262c.216 1.193 1.31 2.027 2.658 2.027h8.282c1.35 0 2.442-.834 2.664-2.072l1.577-13.217h.368c.414 0 .75-.336.75-.75s-.335-.75-.75-.75zM8.496 4.25c0-.413.337-.75.75-.75h5.5c.413 0 .75.337.75.75v.986h-7V4.25zm8.822 15.48c-.1.55-.664.795-1.18.795H7.854c-.517 0-1.083-.246-1.175-.75L5.126 6.735h13.74L17.32 19.732z"></path><path d="M10 17.75c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75zm4 0c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75z"></path></g></svg>
        </div>
      <% end %>
    </li>
  <% end %>

app/views/tweets/_retweet.html.erb
<div class="px-6 py-3 border-b" id="<%= dom_id(tweet) %>">
  <div class="flex items-center mb-3 space-x-2">
    <svg viewBox="0 0 24 24" aria-hidden="true" class="w-4 h-4 fill-current"><g><path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z"></path></g></svg>
    <p class="text-sm font-medium">Retweeted by <%= "@" + tweet.user.username %></p>
  </div>
  <div class="flex space-x-3 items-start">
    <div class= "flex-shrink-0">
      <%= profile_image(tweet.tweet.user) %>
    </div>
    <div class="flex-1">
      <p class="font-bold"><%= link_to tweet.tweet.user.name, profile_path(tweet.tweet.user), class: "hover:underline", data: { turbo: false } %></p>
      <%= link_to tweet, data: {turbo: false} do %>
        <div class="prose prose-lg"><%= tweet.tweet.body %></div>
      <% end %>

      <%= render "tweets/controls", tweet: tweet %>
    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="px-6 py-3 border-b" id="<%= dom_id(tweet) %>">
  <div class="flex space-x-3 items-start">
    <div class= "flex-shrink-0">
      <%= profile_image(tweet.user) %>
    </div>
    <div class="flex-1">
      <p class="font-bold"><%= link_to tweet.user.name, profile_path(tweet.user), class: "hover:underline", data: { turbo: false } %></p>
      <%= link_to tweet, data: {turbo: false} do %>
        <div class="prose prose-lg"><%= tweet.body %></div>
      <% end %>

      <%= render "tweets/controls", tweet: tweet %>
    </div>
  </div>
</div>